name: cosmodex

services:
  db:
    container_name: cosmodex-db
    image: postgres:16-alpine
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d postgres" ]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: YourStrongLocalPassword2024
      POSTGRES_DB: postgres

  redis:
    image: redis:7-alpine
    container_name: cosmodex-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

volumes:
  db-data:
  redisdata:
